Open File - ERROR
MarshalDirectiveException: Type OpenFileName which is passed to unmanaged code must have a StructLayout attribute.
Main.OnGUI () (at Assets/Main.cs:147